### ISSUE TITLE
Encrypting chunks with gpg?

### ISSUE THREAD

**Issue by dpc** [basak/ddar#10]
Hi,

I'm interested in automatic encryption of the chunks using gpg. Is that possible with ddar?

**Comment by basak** [comment]
Not currently. I did have a plan to make generic "chunk filters" possible, allowing for both compression and encryption of chunks. But the sqlite db will not be encrypted this way (perhaps a "db filter" would work with copy-and-replace semantics, but that doesn't really seem very clean).

I use full disk encryption using LUKS on the disks storing my ddar archive which suffices for me.
